#!/usr/bin/env python3.2
#
# This is a simple python script to 
# switch several things in Rellingen 
# on and off
#
# Needs rcswitch-pi and 
# wiringPi installed..

import os
import sys
import time
import datetime

syscodelist = ["11111", "01111"]


# sys.argv[i] describes the ith element typed in.
# for example: command first second results in
#     sys.argv[0] = "path/to/command"
#     sys.argv[1] = "first"
#     sys.argv[2] = "second"

#print(datetime.datetime.now())

if sys.argv[1]=="on": 
	onoff = "1"
elif sys.argv[1]=="off":
	onoff = "0"
else:
	print("I don't know what to do. Sorry.")
	onoff = ""

#socket 1,2,3,4,5 entsprechen A,B,C,D,E
if sys.argv[2]=="N8Lamp":
	socket = "1"
	systemcode = syscodelist[1]
elif sys.argv[2]=="BIGSCREEN":
	systemcode = syscodelist[0]
	socket = "2"
elif sys.argv[2]=="Printer":
	systemcode = syscodelist[0]
	socket = "3"
elif sys.argv[2]=="Variable":
	systemcode = syscodelist[1]
	socket = "4"
elif sys.argv[2]=="LivingRoomLamp":
	systemcode = syscodelist[0]
	socket = "4"
elif sys.argv[2]=="Coffee":
	systemcode = syscodelist[0]
	socket = "5"
elif sys.argv[2]=="TableLamp":
	systemcode = syscodelist[1]
	socket = "2"
elif sys.argv[2]=="KitchenLamp":
	socket = "1"
	systemcode = syscodelist[0]
else:
	print("Something went wrong with setting the socket.")
	print(sys.argv[0],sys.argv[1],sys.argv[2])
	socket = ""
	
send_cmd = "sudo /home/pi/gooseberry/rcswitch-pi/send"
os.system(send_cmd + " " + systemcode + " " +  socket + " " + onoff)
#print("Turned " + sys.argv[2] + " " + sys.argv[1])

# if sys.argv[2]=="Water":
# 	time.sleep(600)
# 	os.system(send_cmd + " " + systemcode + " " +  socket + " " + "0")

